title: "Álvaro Cuéllar"
description: "Investigador en la Universitat Autònoma de Barcelona. Inteligencia Artificial, Lingüística computacional, Patrimonio literario, Teatro del Siglo de Oro, Estilometría, Transcripción automática, Datación automática y Detección de copistas."
timezone: Europe/Madrid
permalink: pretty

# GitHub Pages configuration
url: "https://alvarocuellar.com"
baseurl: ""

markdown: kramdown
highlighter: rouge

# Jekyll Scholar Configuration
plugins:
  - jekyll-scholar
  - jekyll-sitemap

scholar:
  style: apa
  locale: en
  source: _data
  bibliography: publications.bib
  repository: assets/papers
  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

